### ISSUE TITLE
convert - ValueError: Unable to synchronously create group (name already exists)

### ISSUE THREAD

**Issue by gsal** [tdegeus/XDMFWrite_h5py#16]
Just found this handy program....trying to use it. 

Initially, I have two files, one with nodes and connectivity and another with nodal results (attributes).

I read the data and then I write the *.xdmf and *.h5 files with the following code:

```python
hfile = outfile + ".h5"
xfile = outfile + ".xdmf"
with h5py.File(hfile, "w") as h5file, xh.Grid(xfile, ) as xdmf:
    h5file['coor'] = nodes
    h5file['conn'] = cell
    xdmf += xh.Unstructured(h5file["coor"], h5file["conn"], "Tetrahedron")

    for att in nodal.dtype.names:
        h5file[att] = nodal[att]
        xdmf += xh.Attribute(h5file[att], "Node")

print("XDMF/H5 files created successfully.")
```

Then, using meshio, I try to read the file as follows: 

```python
import meshio
mesh = meshio.read("sample.xdmf")
```

but get the following error: 

```bash
Unknown section 'Grid'.
Error: Couldn't read file sample.xdmf as xdmf
```

Inspection of the xdmf file, reveals nested Grid's with the same name "Grid": 

```xml
<?xml version="1.0" ?><Xdmf Version="3.0">	
    <Domain>		
        <Grid CollectionType="Temporal" GridType="Collection" Name="Grid">			
            <Grid Name="Grid">				
                <Geometry GeometryType="XYZ">					
                    <DataItem Dimensions="126400 3" Format="HDF"> sample.h5:/coor </DataItem>					
                </Geometry>				
                <Topology NumberOfElements="551983" TopologyType="Tetrahedron">					
                    <DataItem Dimensions="551983 4" Format="HDF"> sample.h5:/conn </DataItem>
                </Topology>				
                <Attribute AttributeType="Scalar" Center="Node" Name="/AVGL">					
                    <DataItem Dimensions="126400" Format="HDF"> sample.h5:/AVGL </DataItem>					
                </Attribute>				
			.
			.
			.
            </Grid>			
        </Grid>		
    </Domain>	
</Xdmf>
```

If I remove the outer "Temporal" Grid, I am able to read the mesh just fine with meshio. 

BUT, then, if I try to use meshio to convert the *xdmf file to *.h5m, I get the following error: 

```bash
ValueError: Unable to synchronously create group (name already exists)
```

Ideas? 

This is the project file:
```toml
[project]
name = "visualize-this"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "h5py>=3.13.0",
    "jupyterlab",
    "pyvista[all]>=0.45.2",
    "xdmfwrite-h5py>=0.2.0",
]
```
